### ISSUE TITLE
Change password on setting dont work

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#12]
![Screenshot_20200715-084155_Pop](https://user-images.githubusercontent.com/46998867/87486874-3b81ed80-c677-11ea-8d29-508332df27a0.jpg)
![Screenshot_20200715-084202_Pop](https://user-images.githubusercontent.com/46998867/87486877-3cb31a80-c677-11ea-9eaf-ba27db8f08a8.jpg)

Behavior

I am not getting the email verification and will also get the error message when I resend
Beta
Galaxy note 9
1.670001 build 1

**Comment by phooning** [comment]
Change password is a shared screen of forgot password, closing due to duplicate solution for #13
