### ISSUE TITLE
When I click Notification on setting, nothing happen

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#15]
![Screenshot_20200715-085120_Pop](https://user-images.githubusercontent.com/46998867/87487371-6d478400-c678-11ea-93ca-239d3dfea0ac.jpg)

## Behavior
Nothing is happening when I click notification

Beta
Galaxy note 9
1.6700001 build

**Comment by phooning** [comment]
Fixed on android 1.67.2

**Comment by phooning** [comment]
No response from author--tested development-side to work, closing.
