### ISSUE TITLE
Privacy Policy, Content Policy is broken

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#16]
![Screenshot_20200715-085120_Pop](https://user-images.githubusercontent.com/46998867/87487488-bdbee180-c678-11ea-944d-a1a3b4b2d09c.jpg)
![Screenshot_20200715-085254_Samsung Internet](https://user-images.githubusercontent.com/46998867/87487492-bef00e80-c678-11ea-84f3-366197294a57.jpg)

## Behavior

It has the broken link or something is broken on website

Beta
Galaxy 9 note
1.670001

**Comment by phooning** [comment]
Fixed 1.67.2

**Comment by phooning** [comment]
@Yoonsuplee Can you verify once and close this issue if it is resolved for you, thanks

**Comment by phooning** [comment]
No response from author--tested development-side to work, closing.
