### ISSUE TITLE
Inputs getting mixed up during intercom and it is uneditable.

### ISSUE THREAD

**Issue by jsunpop** [pop-your-bubble/organization#33]
During chat analysis, I ran across a chat on 8.21 where a user describes how their name is "Male". I looked in Mongo, and it registered correctly now (keep in mind this happened a couple weeks ago). 

user: 5f76a1dc465400001aff0e4b
 text: lmao yes
 why is your name male lol
 time: 10-2104:23
 
 
user: 5f8cac271c85bc001aa81503
 text: the stupid bot at the beginning renamed me "male" instead of whatever name that i chose!!!
 time: 10-2105:00
 
 
user: 5f8cac271c85bc001aa81503
 text: and it wont let me change it
 time: 10-2105:00
 
 
user: 5f76a1dc465400001aff0e4b
 text: oof
 time: 10-2105:05
 
 
user: 5f8cac271c85bc001aa81503
 text: yeah ikr
 time: 10-2107:07

**Comment by phooning** [comment]
Intercom is removed
