### ISSUE TITLE
iPhone - chat red bubble (unread) not going away

### ISSUE THREAD

**Issue by jsunpop** [pop-your-bubble/organization#35]
"the messages tab says I have 4 messages but I’ve already read all of my messages and I have no unread requests either" - BA

![image](https://user-images.githubusercontent.com/65863977/98629647-eed5b880-22de-11eb-9eb0-239209c9cb16.png)

**Comment by phooning** [comment]
Check if 2.0.36 still gives this issue

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
