### ISSUE TITLE
Duplicating Widgets and Chat Bugs - ASUS Z6 running Android 10

### ISSUE THREAD

**Issue by jsunpop** [pop-your-bubble/organization#36]
I can add the same widget a couple times to my card

![image](https://user-images.githubusercontent.com/65863977/98713357-22e7c280-234d-11eb-86d5-1f28fcc806f1.png)

It's happened for both interests and games
It also prevents me from adding new widgets to my card until i delete one of the duplicates
Also unable to edit the That's My Truth game answers

![image](https://user-images.githubusercontent.com/65863977/98713403-32670b80-234d-11eb-9bca-7543e58826cd.png)

Editing a question widget creates a duplicate
I also seem to be unable to send messages? I click the send button but nothing happens. No new chats appear for me
I'm on a ASUS Z6 running Android 10

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
