### ISSUE TITLE
Modal has been closed error

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#42]
![Screenshot_20201116-172200_Pop](https://user-images.githubusercontent.com/46998867/99320534-78cad780-2831-11eb-9e02-d53b76b3d59e.jpg)

Version 2.00.30 android, galaxy note 9
Behavior:
1. I click heart on widget
2. It pop up the send likes vs optional comment
3. I click back button and modal has closed will pop up
4. I can't get out that state with the screenshot

Additional comment, don't think we need to say modal has been closed, if I back button, it can just get me out of that state immediately.

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
