### ISSUE TITLE
Extra Carousel generation after the filter is applied

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#46]
Android 2.00.30

Can't see the next person and it will always comeback

**Comment by Yoonsuplee** [comment]
https://drive.google.com/file/d/1JLDVDIg88gkqJNYqM9IaW1_T0LY8oETZ/view?usp=sharing

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
