### ISSUE TITLE
Forgot password doesn't work

### ISSUE THREAD

**Issue by phooning** [pop-your-bubble/organization#5]
Has issue of randomly logging out.
Using forgot password's verification code doesn't work.

**Comment by phooning** [comment]
@rskim47 `identity/code` seems to timeout `502` for getting a password reset verification code and entering the right code into the request

**Comment by phooning** [comment]
#13 Enhancement request: change error message to "Please write your email address."

**Comment by beastfromthefareast** [comment]
Fixed
