### ISSUE TITLE
Padding in chat

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#51]
![Screenshot_20201120-173253_Pop](https://user-images.githubusercontent.com/46998867/99859785-b80d6700-2b56-11eb-884d-835ae8531124.jpg)

2.0.30

Android

I think the padding between keyboard and input field could reduced dramatically. Just leave like 1pt. And then also 1pt top above text input box. Also reduce the text input box size height as well. Bit more slime. Less padding on top and bottom of progress bar as well. Also when typing (keyboard is coming up) key board should cover the last text. Text should be above the progress bar padding line.

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
