### ISSUE TITLE
Edit Profile Change

### ISSUE THREAD

**Issue by ruoruowu** [pop-your-bubble/organization#52]
When clicking on the button right profile burton, **this screen** should be shown (not the preview card with the label of 'tap to edit' on the top. The "Edit Profile" on top can be labelled as "My Profile" since the small pencil icons already indicate what can be changed. 

![image](https://user-images.githubusercontent.com/22248577/100119683-fbecbe80-2e2b-11eb-96a1-9acc95cdc365.png)

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
