### ISSUE TITLE
Wallpaper Change Broken (Android)

### ISSUE THREAD

**Issue by ruoruowu** [pop-your-bubble/organization#53]
When I go into my user profile, I see the wallpaper and change wallpaper icons are missing (everything is gray). When I click around the area, I can launch the wallpaper changer but it's not loading anything. 

![image](https://user-images.githubusercontent.com/22248577/100120021-58e87480-2e2c-11eb-8476-12709c36abd4.png)
![image](https://user-images.githubusercontent.com/22248577/100120059-61d94600-2e2c-11eb-9bb5-b91d7ecc8c04.png)

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build (2.1.5) for issues and reopen if necessary.
