### ISSUE TITLE
"Accept Invite" on Invites 

### ISSUE THREAD

**Issue by ruoruowu** [pop-your-bubble/organization#55]
There should be a way for users to accept an invite without the hassle of responding. Screenshot below demos this but you can also find the design in the App Completed section on Figma. 

![image](https://user-images.githubusercontent.com/22248577/100120613-fe034d00-2e2c-11eb-8549-2773ec2d49fe.png)

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
