### ISSUE TITLE
Invite with No Associated Widget

### ISSUE THREAD

**Issue by ruoruowu** [pop-your-bubble/organization#56]
Either a user DMs a user, generating a default invite, or the user comments on/likes a widget, in which case the widget should show up in the invite. Rick said he liked my interests widget so that should show up here. 

![image](https://user-images.githubusercontent.com/22248577/100120722-23905680-2e2d-11eb-9e4c-f8d4273daa3b.png)

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
