### ISSUE TITLE
User's Real Name Shows up in 1:1 Chatroom Header but not Messages

### ISSUE THREAD

**Issue by ruoruowu** [pop-your-bubble/organization#58]
![image](https://user-images.githubusercontent.com/22248577/101087556-38749480-3567-11eb-9965-eca1428f9c9d.png)
![image](https://user-images.githubusercontent.com/22248577/101087587-42969300-3567-11eb-9a75-6da55b466023.png)

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
