### ISSUE TITLE
Chat loading bug

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#59]
Version 2.0.33
Android galaxy note 9
When I click chat room, it shows all loading. 

[Chat loads all of them from begining to end](https://drive.google.com/file/d/1RpMzqNJ81cCD6cGb-LUFsvymdwN-B0cO/view?usp=drivesdk)

**Comment by Yoonsuplee** [comment]
This doesn't happen to some chats and some chats have this problem

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build for issues and reopen if necessary.
