### ISSUE TITLE
Duplicate chat from both side

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#60]
Ver 2.0.33
Android galaxy note 9

![Screenshot_20201204-225135_Pop](https://user-images.githubusercontent.com/46998867/101259572-29b8e980-36ef-11eb-856f-05af5724fd4a.jpg)

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build (2.1.5) for issues and reopen if necessary.
