### ISSUE TITLE
Chat not showing up real time for more than a min

### ISSUE THREAD

**Issue by Yoonsuplee** [pop-your-bubble/organization#61]
Version 2.0.33
Android galaxy note 9

**Comment by Yoonsuplee** [comment]
Got the notification and everything but wont show. Plus it also doesn't show some of our recent conversation either. After a while, it will show and when I come back in its gone again.

**Comment by phooning** [comment]
Closed due to inactivity. See the latest build (2.1.5) for issues and reopen if necessary.
