### ISSUE TITLE
Change Hometown covers original hometown text on text input

### ISSUE THREAD

**Issue by phooning** [pop-your-bubble/organization#7]
## Reproduction
1. Type something

## Expected Behavior
Shouldn't move input box

## Behavior
Input box moves to covers original hometown when something is in the input value

![Simulator Screen Shot - iPhone 11 - 2020-07-08 at 01 09 47](https://user-images.githubusercontent.com/26314517/86883745-22e26800-c0b8-11ea-88d5-f5a24d481b00.png)

**Comment by shenkel7** [comment]
Fixed by wrapping in View!

**Comment by shenkel7** [comment]
(Are permissions off for closing issues? Don't see a button)

**Comment by phooning** [comment]
Tested on iOS and works. Closing issue
